name: citasnuevo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.0.2
  drag_and_drop_gridview: #^2.0.0
    git:
       url: https://github.com/DevOrbiter/drag_and_drop_gridview
  curved_navigation_bar: ^1.0.3
  geolocator: ^9.0.2
  image_picker: ^0.8.4+11
  percent_indicator: ^4.0.0
  flutter_screenutil: ^5.1.1
  firebase_core: ^1.24.0
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^5.0.0+2
  intl: ^0.18.0
  line_awesome_flutter: ^2.0.0
  sleek_circular_slider: ^2.0.1
  google_fonts: ^4.0.0
  location: ^4.3.0
  flutter_datetime_picker_plus: ^2.0.1
  flutter_swiper_plus: ^2.0.4
  path_provider: ^2.0.0
  image_cropper: ^3.0.0
  flutter_image_compress: ^1.1.0
  cached_network_image: ^3.2.1
  permission_handler: ^10.2.0
  transparent_image: ^2.0.0
  another_flushbar: ^1.12.30
  cloud_functions: ^3.2.6
  flutter_launcher_icons: ^0.10.0
  blurhash_dart: ^1.1.0
  flutter_blurhash: ^0.7.0
  octo_image: ^1.0.0
  flutter_holo_date_picker: ^1.0.1+2
  loading_indicator: ^3.0.2
  provider: ^6.0.2
  stack_appodeal_flutter: ^3.0.0
  gdpr_dialog: ^2.1.1

  sliver_header_delegate: ^0.0.1

  async: ^2.4.2
  flash: ^2.0.3+2
  string_validator: ^0.3.0
  equatable: ^2.0.3
  simple_connection_checker: ^0.2.1
  dartz: ^0.10.1
  mockito: ^5.4.2
  ntp: ^2.0.0
  another_xlider: ^1.0.1+2
  wechat_assets_picker: ^8.1.3
  firebase_core_platform_interface: 4.5.1
  giphy_get: 3.4.1
  reorderable_grid_view: ^2.2.6
  flutter_cache_manager: ^3.3.0
  purchases_flutter: ^4.7.0
  firebase_in_app_messaging: ^0.6.0+12
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.3
  flutter_inapp_notifications: ^0.0.3
  notify_inapp: ^0.0.3
  numberpicker: ^2.1.1
  image_compare: ^1.1.2
  flutter_svg: ^1.1.5
  camera: ^0.10.0+1
  appwrite: ^9.0.1
  json_serializable: ^6.5.4
  expandable: ^5.0.1
  flex_seed_scheme: ^1.4.0
  flex_color_scheme: ^7.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.1.8
  test: ^1.24.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/presente.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/presente.png
    - assets/raised_punch_gesture.svg
    - assets/ok_gesture.svg
    - assets/pinching_hand_gesture.svg
    - assets/raised_hand_gesture.svg
    - assets/thumbs_down_gesture.svg
    - assets/thumbs_up_gesture.svg
    - assets/victory_gesture.svg
    - assets/woman_face.svg
    - assets/man_face.svg
    - assets/maybeEmoji.svg
    - assets/likeEmojy.svg
    - assets/passEmoji.svg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
